//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsc_harambe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamAnswer
    {
        public int id { get; set; }
        public int answerID { get; set; }
        public int teamID { get; set; }
        public int eventID { get; set; }
        public Nullable<int> points { get; set; }
        public string answersText { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Event Event { get; set; }
        public virtual Team Team { get; set; }
    }
}
