//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsc_harambe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeam
    {
        public int id { get; set; }
        public int userID { get; set; }
        public int teamID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
